name: 'Hello World Docker Action'
description: 'Say hi to a user somewhere.'
inputs:
  name-of-person:
    description: 'Name of person'
    required: true
    default: 'name'
outputs:
  time:
    description: 'What was the time?.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.name-of-person }}
