name: Hello World test!
on: 
  push:
    branches: [ main ]
    paths: [ hello-world-docker-action/** ]
  workflow_dispatch:

jobs: 
  run-action:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
       uses: actions/checkout@v3
     
     - name: Run helloworld in docker
       id: hello-action
       uses: ./hello-world-docker-action
       with: 
          name-of-person: 'Michael'
     - name: Output time set in the container
       run: echo "The time was ${{ steps.hello-action.outputs.time }} when the action said hello"
